### ISSUE TITLE
加入台灣地區縣市層級的歷史資料

### ISSUE THREAD

**Issue by nondayo** [dspim/COVID-19-Forecasts#3]
資料源：https://nidss.cdc.gov.tw/ch/NIDSS_DiseaseMap.aspx?dc=1&dt=5&disease=19CoV

**Comment by nondayo** [comment]
@JohnsonHsieh  [這段](https://github.com/dspim/COVID-19-Forecasts/blob/feature/tw_cdc_crawler/R/updateForecasts.R#L116)在跑 `tw_county.csv` 的起始時間設定會出錯，請問預設是從哪天開始呢？

**Comment by JohnsonHsieh** [comment]
02-01
